/* The following code was generated by JFlex 1.6.1 */

package com.pcl.lexer;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/kevinah95/IdeaProjects/pcl-compiler/src/com/pcl/lexer/pcl.flex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\71\1\72\1\1\16\7\4\0\1\3\1\50"+
    "\1\17\1\0\1\6\1\60\1\54\1\20\1\35\1\36\1\5\1\56"+
    "\1\44\1\16\1\14\1\4\1\10\1\62\1\61\1\66\1\63\1\11"+
    "\1\67\1\64\1\65\1\11\1\53\1\43\1\47\1\45\1\46\1\52"+
    "\1\0\3\6\1\70\1\15\1\13\5\6\1\12\16\6\1\41\1\21"+
    "\1\42\1\57\1\6\1\0\1\22\1\23\1\27\1\70\1\31\1\32"+
    "\5\6\1\33\1\6\1\34\3\6\1\26\1\24\1\25\1\30\5\6"+
    "\1\37\1\55\1\40\1\51\6\7\1\73\32\7\2\0\4\6\4\0"+
    "\1\6\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6\1\0"+
    "\37\6\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6\1\0"+
    "\1\6\21\0\160\7\5\6\1\0\2\6\2\0\4\6\10\0\1\6"+
    "\1\0\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0\213\6"+
    "\1\0\5\7\2\0\236\6\11\0\46\6\2\0\1\6\7\0\47\6"+
    "\7\0\1\6\1\0\55\7\1\0\1\7\1\0\2\7\1\0\2\7"+
    "\1\0\1\7\10\0\33\6\5\0\3\6\15\0\5\7\6\0\1\6"+
    "\4\0\13\7\5\0\53\6\37\7\4\0\2\6\1\7\143\6\1\0"+
    "\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6\12\7"+
    "\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7\2\0"+
    "\131\6\13\7\1\6\16\0\12\7\41\6\11\7\2\6\4\0\1\6"+
    "\5\0\26\6\4\7\1\6\11\7\1\6\3\7\1\6\5\7\22\0"+
    "\31\6\3\7\104\0\1\6\1\0\13\6\67\0\33\7\1\0\4\7"+
    "\66\6\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0\12\7"+
    "\1\0\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0\1\7"+
    "\1\6\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7\4\0"+
    "\2\6\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6\5\0"+
    "\3\7\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6\1\0"+
    "\2\6\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7\4\0"+
    "\2\7\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6\7\0"+
    "\14\7\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6\1\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7\1\6"+
    "\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6\2\7"+
    "\2\0\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0\2\6"+
    "\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7"+
    "\1\6\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0\2\6"+
    "\1\0\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7\1\6"+
    "\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6"+
    "\1\0\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0\5\7"+
    "\3\0\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0\12\7"+
    "\11\0\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0\27\6"+
    "\1\0\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7\1\0"+
    "\4\7\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0\12\7"+
    "\22\0\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0\12\6"+
    "\1\0\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0\4\7"+
    "\7\0\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7\1\0"+
    "\2\6\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6\2\0"+
    "\1\6\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7\10\0"+
    "\2\6\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0\22\6"+
    "\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\7"+
    "\4\0\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0\60\6"+
    "\1\7\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0\4\6"+
    "\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0\2\6"+
    "\1\0\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0\5\6"+
    "\1\0\1\6\1\0\6\7\2\0\12\7\2\0\4\6\40\0\1\6"+
    "\27\0\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0\1\7"+
    "\4\0\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7\5\6"+
    "\13\7\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6\12\7"+
    "\6\0\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7\3\6"+
    "\4\7\15\6\14\7\1\6\17\7\2\0\46\6\1\0\1\6\5\0"+
    "\1\6\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6\1\0"+
    "\1\6\1\0\4\6\2\0\51\6\1\0\4\6\2\0\41\6\1\0"+
    "\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\17\6\1\0"+
    "\71\6\1\0\4\6\2\0\103\6\2\0\3\7\40\0\20\6\20\0"+
    "\125\6\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6\3\0"+
    "\3\6\17\0\15\6\1\0\4\6\3\7\13\0\22\6\3\7\13\0"+
    "\22\6\2\7\14\0\15\6\1\0\3\6\1\0\2\7\14\0\64\6"+
    "\40\7\3\0\1\6\3\0\2\6\1\7\2\0\12\7\41\0\3\7"+
    "\2\0\12\7\6\0\130\6\10\0\51\6\1\7\1\6\5\0\106\6"+
    "\12\0\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6\2\0"+
    "\5\6\13\0\54\6\4\0\21\7\7\6\2\7\6\0\12\7\46\0"+
    "\27\6\5\7\4\0\65\6\12\7\1\0\35\7\2\0\13\7\6\0"+
    "\12\7\15\0\1\6\130\0\5\7\57\6\21\7\7\6\4\0\12\7"+
    "\21\0\11\7\14\0\3\7\36\6\15\7\2\6\12\7\54\6\16\7"+
    "\14\0\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6\122\0"+
    "\3\7\1\0\25\7\4\6\1\7\4\6\3\7\2\6\11\0\300\6"+
    "\47\7\25\0\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0\6\6"+
    "\2\0\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6"+
    "\2\0\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6"+
    "\3\0\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6"+
    "\16\0\5\7\30\0\1\71\1\71\5\7\20\0\2\6\23\0\1\6"+
    "\13\0\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0\15\6"+
    "\3\0\33\6\25\0\15\7\4\0\1\7\3\0\14\7\21\0\1\6"+
    "\4\0\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6"+
    "\1\0\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6"+
    "\5\0\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6"+
    "\1\0\205\6\6\0\4\6\3\7\2\6\14\0\46\6\1\0\1\6"+
    "\5\0\1\6\2\0\70\6\7\0\1\6\17\0\1\7\27\6\11\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0"+
    "\7\6\1\0\7\6\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0"+
    "\3\6\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6"+
    "\2\0\2\7\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6"+
    "\3\0\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6"+
    "\63\0\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6"+
    "\24\0\57\6\1\7\4\0\12\7\1\0\31\6\7\0\1\7\120\6"+
    "\2\7\45\0\11\6\2\0\147\6\2\0\4\6\1\0\4\6\14\0"+
    "\13\6\115\0\12\6\1\7\3\6\1\7\4\6\1\7\27\6\5\7"+
    "\20\0\1\6\7\0\64\6\14\0\2\7\62\6\21\7\13\0\12\7"+
    "\6\0\22\7\6\6\3\0\1\6\4\0\12\7\34\6\10\7\2\0"+
    "\27\6\15\7\14\0\35\6\3\0\4\7\57\6\16\7\16\0\1\6"+
    "\12\7\46\0\51\6\16\7\11\0\3\6\1\7\10\6\2\7\2\0"+
    "\12\7\6\0\27\6\3\0\1\6\1\7\4\0\60\6\1\7\1\6"+
    "\3\7\2\6\2\7\5\6\2\7\1\6\1\7\1\6\30\0\3\6"+
    "\2\0\13\6\5\7\2\0\3\6\2\7\12\0\6\6\2\0\6\6"+
    "\2\0\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\7\1\0"+
    "\2\7\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0"+
    "\u016e\6\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\7"+
    "\12\6\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0"+
    "\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0"+
    "\15\6\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6\31\0"+
    "\1\6\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6\13\0"+
    "\12\7\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0"+
    "\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0"+
    "\2\6\22\0\3\7\4\0\14\6\1\0\32\6\1\0\23\6\1\0"+
    "\2\6\1\0\17\6\2\0\16\6\42\0\173\6\105\0\65\6\210\0"+
    "\1\7\202\0\35\6\3\0\61\6\57\0\37\6\21\0\33\6\65\0"+
    "\36\6\2\0\44\6\4\0\10\6\1\0\5\6\52\0\236\6\2\0"+
    "\12\7\u0356\0\6\6\2\0\1\6\1\0\54\6\1\0\2\6\3\0"+
    "\1\6\2\0\27\6\252\0\26\6\12\0\32\6\106\0\70\6\6\0"+
    "\2\6\100\0\1\6\3\7\1\0\2\7\5\0\4\7\4\6\1\0"+
    "\3\6\1\0\33\6\4\0\3\7\4\0\1\7\40\0\35\6\203\0"+
    "\66\6\12\0\26\6\12\0\23\6\215\0\111\6\u03b7\0\3\7\65\6"+
    "\17\7\37\0\12\7\20\0\3\7\55\6\13\7\2\0\1\7\22\0"+
    "\31\6\7\0\12\7\6\0\3\7\44\6\16\7\1\0\12\7\100\0"+
    "\3\7\60\6\16\7\4\6\13\0\12\7\u04a6\0\53\6\15\7\10\0"+
    "\12\7\u0936\0\u036f\6\221\0\143\6\u0b9d\0\u042f\6\u33d1\0\u0239\6\u04c7\0"+
    "\105\6\13\0\1\6\56\7\20\0\4\7\15\6\u4060\0\2\6\u2163\0"+
    "\5\7\3\0\26\7\2\0\7\7\36\0\4\7\224\0\3\7\u01bb\0"+
    "\125\6\1\0\107\6\1\0\2\6\2\0\1\6\2\0\2\6\2\0"+
    "\4\6\1\0\14\6\1\0\1\6\1\0\7\6\1\0\101\6\1\0"+
    "\4\6\2\0\10\6\1\0\7\6\1\0\34\6\1\0\4\6\1\0"+
    "\5\6\1\0\1\6\3\0\7\6\1\0\u0154\6\2\0\31\6\1\0"+
    "\31\6\1\0\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0"+
    "\37\6\1\0\31\6\1\0\37\6\1\0\31\6\1\0\10\6\2\0"+
    "\62\7\u1600\0\4\6\1\0\33\6\1\0\2\6\1\0\1\6\2\0"+
    "\1\6\1\0\12\6\1\0\4\6\1\0\1\6\1\0\1\6\6\0"+
    "\1\6\4\0\1\6\1\0\1\6\1\0\1\6\1\0\3\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\2\6\1\0\1\6\2\0\4\6\1\0"+
    "\7\6\1\0\4\6\1\0\4\6\1\0\1\6\1\0\12\6\1\0"+
    "\21\6\5\0\3\6\1\0\5\6\1\0\21\6\u1144\0\ua6d7\6\51\0"+
    "\u1035\6\13\0\336\6\u3fe2\0\u021e\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\7\36\0\140\7\200\0\360\7\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\2\6\1\7"+
    "\1\10\1\11\1\12\4\5\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\2\40\1\41\2\1\2\42\1\1\1\2\1\0"+
    "\1\43\1\44\1\45\1\46\1\47\1\45\1\0\1\50"+
    "\1\51\1\52\1\0\4\5\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\70\1\71\1\72\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\1\101\1\102\10\71\1\0\1\45\2\0"+
    "\4\5\1\103\1\104\1\105\1\106\1\107\1\110\1\111"+
    "\1\112\1\113\1\114\1\115\1\0\1\5\1\116\1\5"+
    "\1\117\1\120\1\0\1\5\1\121\1\0\1\5\1\0"+
    "\1\5\1\0\1\122\2\0\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\264\0\u012c\0\u0168"+
    "\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\264\0\264\0\u02d0"+
    "\0\u030c\0\u0348\0\u0384\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\u03c0\0\u03fc\0\u0438\0\u0474\0\264"+
    "\0\264\0\264\0\u04b0\0\u04ec\0\u0528\0\u0564\0\u05a0\0\u05dc"+
    "\0\u0618\0\264\0\264\0\u0654\0\u0690\0\u06cc\0\264\0\u0708"+
    "\0\u0744\0\u0780\0\264\0\264\0\u07bc\0\264\0\264\0\u07f8"+
    "\0\u0834\0\264\0\264\0\264\0\u0870\0\u08ac\0\u08e8\0\u0924"+
    "\0\u0960\0\264\0\264\0\u099c\0\264\0\u09d8\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c"+
    "\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c"+
    "\0\u0d98\0\264\0\u0dd4\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\264\0\264\0\264\0\u0e10\0\u0e4c\0\u01a4\0\u0e88"+
    "\0\u01a4\0\264\0\u0ec4\0\u0f00\0\u01a4\0\u0f3c\0\u0f78\0\u0fb4"+
    "\0\u0ff0\0\u102c\0\u01a4\0\u1068\0\u10a4\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\2\11\1\14\1\11\1\15\1\16\1\17\1\4"+
    "\1\20\2\11\1\21\4\11\1\22\1\11\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\7\13\1\11\1\4\1\6\1\4"+
    "\1\50\1\51\1\52\14\50\1\53\1\50\1\54\52\50"+
    "\1\55\1\56\1\57\15\55\1\4\1\60\52\55\76\0"+
    "\1\6\75\0\1\61\1\62\37\0\1\63\73\0\1\64"+
    "\34\0\6\11\1\0\1\11\4\0\13\11\24\0\10\11"+
    "\2\0\1\11\10\0\2\65\1\66\1\67\1\70\1\71"+
    "\13\0\1\71\1\67\1\66\25\0\7\65\1\72\13\0"+
    "\2\13\1\66\1\67\1\70\1\71\13\0\1\71\1\67"+
    "\1\66\25\0\7\13\1\72\13\0\2\70\47\0\7\70"+
    "\22\0\1\73\26\0\1\74\13\0\1\75\20\0\6\11"+
    "\1\0\1\11\4\0\1\11\1\76\11\11\24\0\10\11"+
    "\2\0\1\11\6\0\6\11\1\0\1\11\4\0\4\11"+
    "\1\77\6\11\24\0\10\11\2\0\1\11\6\0\6\11"+
    "\1\0\1\11\4\0\1\100\12\11\24\0\10\11\2\0"+
    "\1\11\6\0\6\11\1\0\1\11\4\0\6\11\1\101"+
    "\4\11\24\0\10\11\2\0\1\11\45\0\1\102\73\0"+
    "\1\103\1\104\72\0\1\105\1\0\1\106\71\0\1\107"+
    "\73\0\1\110\6\0\1\111\64\0\1\112\7\0\1\113"+
    "\63\0\1\114\10\0\1\115\62\0\1\116\73\0\1\117"+
    "\26\0\1\50\2\0\14\50\1\0\1\50\1\0\52\50"+
    "\2\0\1\52\71\0\1\120\2\0\14\120\1\121\1\122"+
    "\1\123\1\120\1\124\1\120\1\125\1\126\3\120\1\127"+
    "\1\120\1\130\34\120\23\0\1\131\55\0\1\57\71\0"+
    "\1\120\2\0\14\120\1\132\1\133\1\134\1\120\1\135"+
    "\1\120\1\136\1\137\3\120\1\140\1\120\1\141\34\120"+
    "\3\0\1\61\1\5\1\6\71\61\5\62\1\142\66\62"+
    "\10\0\2\65\1\0\1\67\1\70\1\71\13\0\1\71"+
    "\1\67\26\0\7\65\1\72\13\0\2\70\1\0\1\67"+
    "\1\0\1\71\13\0\1\71\1\67\26\0\7\70\1\72"+
    "\13\0\2\143\4\0\1\144\37\0\1\144\2\0\7\143"+
    "\66\0\1\145\17\0\6\11\1\0\1\11\4\0\2\11"+
    "\1\146\10\11\24\0\10\11\2\0\1\11\6\0\6\11"+
    "\1\0\1\11\4\0\6\11\1\147\4\11\24\0\10\11"+
    "\2\0\1\11\6\0\6\11\1\0\1\11\4\0\11\11"+
    "\1\150\1\11\24\0\10\11\2\0\1\11\6\0\6\11"+
    "\1\0\1\11\4\0\11\11\1\151\1\11\24\0\10\11"+
    "\2\0\1\11\45\0\1\152\1\153\72\0\1\154\46\0"+
    "\1\155\73\0\1\156\73\0\1\157\73\0\1\160\73\0"+
    "\1\161\73\0\1\162\73\0\1\163\73\0\1\164\53\0"+
    "\4\62\1\6\1\142\66\62\10\0\2\143\1\0\1\67"+
    "\16\0\1\67\26\0\7\143\1\72\13\0\2\143\47\0"+
    "\7\143\67\0\1\165\16\0\6\11\1\0\1\11\4\0"+
    "\3\11\1\166\7\11\24\0\10\11\2\0\1\11\6\0"+
    "\6\11\1\0\1\11\4\0\7\11\1\167\3\11\24\0"+
    "\10\11\2\0\1\11\6\0\6\11\1\0\1\11\4\0"+
    "\2\11\1\170\10\11\24\0\10\11\2\0\1\11\6\0"+
    "\6\11\1\0\1\11\4\0\11\11\1\171\1\11\24\0"+
    "\10\11\2\0\1\11\45\0\1\172\112\0\1\173\15\0"+
    "\6\11\1\0\1\11\4\0\4\11\1\174\6\11\24\0"+
    "\10\11\2\0\1\11\6\0\6\11\1\0\1\11\4\0"+
    "\7\11\1\175\3\11\24\0\10\11\2\0\1\11\63\0"+
    "\1\176\16\0\6\11\1\0\1\11\4\0\1\177\12\11"+
    "\24\0\10\11\2\0\1\11\65\0\1\200\14\0\6\11"+
    "\1\0\1\11\4\0\5\11\1\201\5\11\24\0\10\11"+
    "\2\0\1\11\66\0\1\202\13\0\6\11\1\0\1\11"+
    "\4\0\3\11\1\203\7\11\24\0\10\11\2\0\1\11"+
    "\67\0\1\204\67\0\1\205\75\0\1\206\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4320];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\7\1\2\11\4\1\10\11"+
    "\4\1\3\11\7\1\2\11\3\1\1\11\2\1\1\0"+
    "\2\11\1\1\2\11\1\1\1\0\3\11\1\0\4\1"+
    "\2\11\1\1\1\11\1\1\23\11\10\1\1\0\1\1"+
    "\2\0\4\1\1\11\1\1\11\11\1\0\4\1\1\11"+
    "\1\0\2\1\1\0\1\1\1\0\1\1\1\0\1\1"+
    "\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[134];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuilder string = new StringBuilder();

  private Symbol symbol(int type) {
    return new PclSymbol(type, yyline+1, yycolumn+1);
  }

  private Symbol symbol(int type, Object value) {
    return new PclSymbol(type, yyline+1, yycolumn+1, value);
  }




  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2870) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
            }
          case 84: break;
          case 2: 
            { /* ignore */
            }
          case 85: break;
          case 3: 
            { return symbol(DIV);
            }
          case 86: break;
          case 4: 
            { return symbol(MULT);
            }
          case 87: break;
          case 5: 
            { return symbol(IDENTIFIER, yytext());
            }
          case 88: break;
          case 6: 
            { return symbol(INTEGER_LITERAL, new Integer(yytext()));
            }
          case 89: break;
          case 7: 
            { return symbol(DOT);
            }
          case 90: break;
          case 8: 
            { return symbol(MINUS);
            }
          case 91: break;
          case 9: 
            { yybegin(STRING); string.setLength(0);
            }
          case 92: break;
          case 10: 
            { yybegin(CHARLITERAL);
            }
          case 93: break;
          case 11: 
            { return symbol(LPAREN);
            }
          case 94: break;
          case 12: 
            { return symbol(RPAREN);
            }
          case 95: break;
          case 13: 
            { return symbol(LBRACE);
            }
          case 96: break;
          case 14: 
            { return symbol(RBRACE);
            }
          case 97: break;
          case 15: 
            { return symbol(LBRACK);
            }
          case 98: break;
          case 16: 
            { return symbol(RBRACK);
            }
          case 99: break;
          case 17: 
            { return symbol(SEMICOLON);
            }
          case 100: break;
          case 18: 
            { return symbol(COMMA);
            }
          case 101: break;
          case 19: 
            { return symbol(EQ);
            }
          case 102: break;
          case 20: 
            { return symbol(GT);
            }
          case 103: break;
          case 21: 
            { return symbol(LT);
            }
          case 104: break;
          case 22: 
            { return symbol(NOT);
            }
          case 105: break;
          case 23: 
            { return symbol(COMP);
            }
          case 106: break;
          case 24: 
            { return symbol(QUESTION);
            }
          case 107: break;
          case 25: 
            { return symbol(COLON);
            }
          case 108: break;
          case 26: 
            { return symbol(AND);
            }
          case 109: break;
          case 27: 
            { return symbol(OR);
            }
          case 110: break;
          case 28: 
            { return symbol(PLUS);
            }
          case 111: break;
          case 29: 
            { return symbol(XOR);
            }
          case 112: break;
          case 30: 
            { return symbol(MOD);
            }
          case 113: break;
          case 31: 
            { string.append( yytext() );
            }
          case 114: break;
          case 32: 
            { throw new RuntimeException("Unterminated string at end of line");
            }
          case 115: break;
          case 33: 
            { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
            }
          case 116: break;
          case 34: 
            { throw new RuntimeException("Unterminated character literal at end of line");
            }
          case 117: break;
          case 35: 
            { return symbol(DIVEQ);
            }
          case 118: break;
          case 36: 
            { return symbol(MULTEQ);
            }
          case 119: break;
          case 37: 
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
            }
          case 120: break;
          case 38: 
            { return symbol(INTEGER_LITERAL, new Long(yytext().substring(0,yylength()-1)));
            }
          case 121: break;
          case 39: 
            { return symbol(FLOATING_POINT_LITERAL, new Float(yytext().substring(0,yylength()-1)));
            }
          case 122: break;
          case 40: 
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext().substring(0,yylength()-1)));
            }
          case 123: break;
          case 41: 
            { return symbol(MINUSMINUS);
            }
          case 124: break;
          case 42: 
            { return symbol(MINUSEQ);
            }
          case 125: break;
          case 43: 
            { return symbol(EQEQ);
            }
          case 126: break;
          case 44: 
            { return symbol(GTEQ);
            }
          case 127: break;
          case 45: 
            { return symbol(RSHIFT);
            }
          case 128: break;
          case 46: 
            { return symbol(LTEQ);
            }
          case 129: break;
          case 47: 
            { return symbol(LSHIFT);
            }
          case 130: break;
          case 48: 
            { return symbol(NOTEQ);
            }
          case 131: break;
          case 49: 
            { return symbol(ANDEQ);
            }
          case 132: break;
          case 50: 
            { return symbol(ANDAND);
            }
          case 133: break;
          case 51: 
            { return symbol(OREQ);
            }
          case 134: break;
          case 52: 
            { return symbol(OROR);
            }
          case 135: break;
          case 53: 
            { return symbol(PLUSEQ);
            }
          case 136: break;
          case 54: 
            { return symbol(PLUSPLUS);
            }
          case 137: break;
          case 55: 
            { return symbol(XOREQ);
            }
          case 138: break;
          case 56: 
            { return symbol(MODEQ);
            }
          case 139: break;
          case 57: 
            { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
            }
          case 140: break;
          case 58: 
            { string.append( '\"' );
            }
          case 141: break;
          case 59: 
            { string.append( '\'' );
            }
          case 142: break;
          case 60: 
            { string.append( '\\' );
            }
          case 143: break;
          case 61: 
            { string.append( '\b' );
            }
          case 144: break;
          case 62: 
            { string.append( '\t' );
            }
          case 145: break;
          case 63: 
            { string.append( '\r' );
            }
          case 146: break;
          case 64: 
            { string.append( '\f' );
            }
          case 147: break;
          case 65: 
            { string.append( '\n' );
            }
          case 148: break;
          case 66: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, yytext().charAt(0));
            }
          case 149: break;
          case 67: 
            { return symbol(RSHIFTEQ);
            }
          case 150: break;
          case 68: 
            { return symbol(URSHIFT);
            }
          case 151: break;
          case 69: 
            { return symbol(LSHIFTEQ);
            }
          case 152: break;
          case 70: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\"');
            }
          case 153: break;
          case 71: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\'');
            }
          case 154: break;
          case 72: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\\');
            }
          case 155: break;
          case 73: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\b');
            }
          case 156: break;
          case 74: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\t');
            }
          case 157: break;
          case 75: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\r');
            }
          case 158: break;
          case 76: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\f');
            }
          case 159: break;
          case 77: 
            { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, '\n');
            }
          case 160: break;
          case 78: 
            { return symbol(BOOLEAN_LITERAL, true);
            }
          case 161: break;
          case 79: 
            { return symbol(NULL_LITERAL);
            }
          case 162: break;
          case 80: 
            { return symbol(URSHIFTEQ);
            }
          case 163: break;
          case 81: 
            { return symbol(BOOLEAN_LITERAL, false);
            }
          case 164: break;
          case 82: 
            { return symbol(ABSTRACT);
            }
          case 165: break;
          case 83: 
            { return symbol(INTEGER_LITERAL, new Integer(Integer.MIN_VALUE));
            }
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
