
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 07 16:18:12 CST 2016
//----------------------------------------------------

package com.pcl.lexer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int IDENTIFIER = 2;
  public static final int REAL = 32;
  public static final int GT = 58;
  public static final int PACKED = 28;
  public static final int DIV_SYM = 66;
  public static final int TYPE = 41;
  public static final int READ = 31;
  public static final int CONST = 9;
  public static final int PLUSEQ = 74;
  public static final int UNTIL = 42;
  public static final int RBRACK = 70;
  public static final int COMMA = 53;
  public static final int RPAREN = 68;
  public static final int LBRACK = 69;
  public static final int LT = 60;
  public static final int LPAREN = 67;
  public static final int INTEGER_LITERAL = 83;
  public static final int FALSE = 14;
  public static final int NOT = 48;
  public static final int NIL = 26;
  public static final int ARRAY = 3;
  public static final int VAR = 43;
  public static final int INLINE = 22;
  public static final int THEN = 38;
  public static final int GOTO = 19;
  public static final int RECORD = 33;
  public static final int EQ = 62;
  public static final int BOOLEAN_LITERAL = 85;
  public static final int MOD = 52;
  public static final int WRITE = 46;
  public static final int TRUE = 40;
  public static final int PLUS = 63;
  public static final int WHILE = 44;
  public static final int ASSIGN = 71;
  public static final int CHAR = 8;
  public static final int BOOLEAN = 5;
  public static final int LONGINT = 25;
  public static final int SHORTINT = 36;
  public static final int DO = 10;
  public static final int FOR = 16;
  public static final int RSHIFTEQ = 81;
  public static final int DIV = 51;
  public static final int DOWNTO = 11;
  public static final int MULT = 65;
  public static final int ELSE = 12;
  public static final int GTEQ = 57;
  public static final int DOT = 72;
  public static final int PROCEDURE = 29;
  public static final int INT = 23;
  public static final int STRING_LITERAL = 82;
  public static final int EOF = 0;
  public static final int SEMICOLON = 54;
  public static final int FUNCTION = 18;
  public static final int MULTEQ = 76;
  public static final int REPEAT = 34;
  public static final int LABEL = 24;
  public static final int MINUS = 64;
  public static final int LTEQ = 59;
  public static final int IN = 21;
  public static final int OR = 49;
  public static final int SET = 35;
  public static final int error = 1;
  public static final int DIVEQ = 77;
  public static final int LSHIFTEQ = 80;
  public static final int IF = 20;
  public static final int MINUSMINUS = 56;
  public static final int OF = 27;
  public static final int END = 13;
  public static final int COLON = 73;
  public static final int FILE = 15;
  public static final int CHARACTER_LITERAL = 86;
  public static final int BEGIN = 4;
  public static final int CASE = 7;
  public static final int PLUSPLUS = 55;
  public static final int FORWARD = 17;
  public static final int RSHIFT = 78;
  public static final int STRING = 37;
  public static final int NEQ = 61;
  public static final int PROGRAM = 30;
  public static final int BYTE = 6;
  public static final int AND = 47;
  public static final int TO = 39;
  public static final int LSHIFT = 79;
  public static final int WITH = 45;
  public static final int XOR = 50;
  public static final int FLOATING_POINT_LITERAL = 84;
  public static final int MINUSEQ = 75;
}

