
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 02 23:00:19 CST 2016
//----------------------------------------------------

package com.pcl.lexer;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int OPERADOR = 3;
  public static final int LITERAL = 5;
  public static final int BOOLEAN_LITERAL = 9;
  public static final int PALABRA_RESERVADA = 4;
  public static final int CHARACTER_LITERAL = 10;
  public static final int STRING_LITERAL = 6;
  public static final int EOF = 0;
  public static final int FLOATING_POINT_LITERAL = 8;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 2;
  public static final int INTEGER_LITERAL = 7;
}

